### ISSUE TITLE
Page freezes when using `Proxy`

### ISSUE THREAD

**Issue by still-soda** [jsrepl/jsrepl.io#3]
# Page freezes when using `Proxy`

## Description

When writing native JavaScript code in the editor, the page freezes immediately after defining a `Proxy` object and inputting an empty block `{}` in the `get` method. The page becomes unresponsive and no further actions can be performed.

## Steps to Reproduce:

1. Open the editor.
2. Enter the following code:
    ```javascript
    const obj = { a: 20 };
    
    const proxy = new Proxy(obj, {
      get(target, p){} 
    })
    ```
3. Press Enter.
4. The page freezes and becomes unresponsive.

## Expected Behavior

The page should properly handle the `Proxy` definition without freezing or entering an infinite loop.

## Current Behavior

The page freezes without any error message, and it seems like an infinite loop occurs. The developer tools cannot be opened during this process.

## Environment Information:

- **Browser**: Edge v132.0.2957.55
- **Additional Configuration**: The issue occurs while writing native JavaScript using `Proxy`.

**Comment by al3xnag** [comment]
Thanks for reporting! 

You actually discovered at least 2 different problems in the jsrepl implementation. I'm working on a fix. Proxies are tricky, but I'll try to support them properly.

**Comment by al3xnag** [comment]
For the record:

A similar problem with infinite loop, but the page doesn't freeze. JSRepl handles circular refs, but it doesn't work for the reported issue and in the following case

<img width="1059" alt="Image" src="https://github.com/user-attachments/assets/962e55b8-6696-4c41-8413-fe7965eb9023" />
